### PR TITLE
Fix always open menu on article sidebar after selection

### LINKED ISSUE #594: Fix always open menu on article sidebar after selection
## Context

After selecting a option on the sidebar menu or cllicking away the menu should close.

Here's an example of it staying open when you open the report modal:

Screenshot 2023-10-24 at 11 31 53

Make sure this behavior is the same on mobile too! 🦾 

## Expected Behavior

The menu should close after you choose and option or click away from the menu. 

## Steps to reproduce

1. Go to any article
2. Select the menu on the left
3. Select "Report article" to view the modal

### PR DESCRIPTION
**Pull request by seog-jun**
# ✨ Codu Pull Request 💻

Codu Logo

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## Pull Request details:
Fixes #594 
Fixed the issue that `Popover.panel` always opens when `Report Article` is clicked. 

## Any Breaking changes:
None

## Associated Screenshots:

https://github.com/codu-code/codu/assets/88434287/30345ea8-c828-425f-aa7b-6f950e676d4d

p.s: Let me know if there's something not working or I'm missing, Thanks!

### CODE REVIEW

File: components/ArticleMenu/ArticleMenu.tsx [hunk 1]
```diff
@@ -164,7 +176,10 @@ const ArticleMenu = ({
               leaveFrom="transform opacity-100 scale-100"
               leaveTo="transform opacity-0 scale-95"
             >
-              <Popover.Panel className="origin-top-right absolute bottom-14 right-0 lg:left-16 lg:bottom-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white dark:bg-white ring-1 px-1 ring-black ring-opacity-5 focus:outline-none">
+              <Popover.Panel
```
Comment (NiallJoeMaher) [inline components/ArticleMenu/ArticleMenu.tsx:179]: Rather than styling, do you think this might be a cleaner solution? https://headlessui.com/react/popover#closing-popovers-manually This lets you use the internal popover state to close things. 

Let me know what you think!

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Thanks for this! Only one question/suggestion. 🦾

**Comment by seog-jun** [comment]
@NiallJoeMaher Hi, let me know if there are more questions/suggestions about it. Just for a reminder, this PR is still not merged yet.

**Comment by NiallJoeMaher** [comment]
> @NiallJoeMaher Hi, let me know if there are more questions/suggestions about it. Just for a reminder, this PR is still not merged yet.

Hey! Yes, I added a change request but didn't see any comments or updates, so I was waiting for that. 🦾  Let me know if I can help with anything.

**Comment by seog-jun** [comment]
> > @NiallJoeMaher Hi, let me know if there are more questions/suggestions about it. Just for a reminder, this PR is still not merged yet.
> 
> Hey! Yes, I added a change request but didn't see any comments or updates, so I was waiting for that. 🦾 Let me know if I can help with anything.

Oh I left comment under your reply, but it was pending, sorry about that! And this is my reply:

@NiallJoeMaher
Thanks for your feedback! I also thought this would be a clearer solution and I already approached this way However, when I use Popover.Button with ReportModal component, ReportModal component shows up and disappears in a second because Popover.Button closes the the whole Popover.Panel . Maybe I'm wrong, but it didn't really work for me, that's the reason why I used styling as a workaround.

**Comment by NiallJoeMaher** [comment]
> > > @NiallJoeMaher Hi, let me know if there are more questions/suggestions about it. Just for a reminder, this PR is still not merged yet.
> > 
> > 
> > Hey! Yes, I added a change request but didn't see any comments or updates, so I was waiting for that. 🦾 Let me know if I can help with anything.
> 
> Oh I left comment under your reply, but it was pending, sorry about that! And this is my reply:
> 
> @NiallJoeMaher Thanks for your feedback! I also thought this would be a clearer solution and I already approached this way However, when I use Popover.Button with ReportModal component, ReportModal component shows up and disappears in a second because Popover.Button closes the the whole Popover.Panel . Maybe I'm wrong, but it didn't really work for me, that's the reason why I used styling as a workaround.

Perfect let me test it and get back to you! If it isn't work as I hoped I'll get this merged. Thanks!

**Review by NiallJoeMaher — APPROVED** [review]
LGTM! I'm not sure why the build is breaking but we will get there. 😢

**Comment by seog-jun** [comment]
@NiallJoeMaher Thanks for the review! Let me know if there's something that I have to fix for the build.

**Comment by NiallJoeMaher** [comment]
Sorry about the delay! I had a nightmare over the last few days with my AWS pipeline! Thanks for the work. 🦾
